<?php

define('USUARIO_KEY', $_ENV['TOKEN_KEY'] . '=USUARIOS');
define('ACARREO_KEY', $_ENV['TOKEN_KEY'] . '=ACARREO');
define('LIBRETASANITARIA_KEY', $_ENV['TOKEN_KEY'] . '=LIBRETASANITARIA');
define('EMPLEADO_KEY', $_ENV['TOKEN_KEY'] . '=EMPLEADO');
define('LOGIN_KEY', $_ENV['TOKEN_KEY'] . '=LOGIN');
define('LICENCIA_KEY', $_ENV['TOKEN_KEY'] . '=LICENCIA');
